Bug Fixes and New Presentation Material (#4)
* objFunc update

Added sample functions to the file as comments. They are all n-variable
functions, meaning they can be generalized to as many dimensions as
desired.

Also added some markup for Matlab Publish

* Updating objFunc.m

-Added various n-dimensional functions to test optimization with,
categorized them into different categories to help analyze the
effectiveness of the algorithm

-Added documentation

-Added non-vectorized psuedo code for evaluating function.

* test

test

* objFunc fix

Fixed the loop under the testing purposes comment so that it runs based
on the number of rows, not columns.

* objFunc Fix

Added comments

* Presentation, Anneal Flowchart, Simple Chart

See title. no changes to code

* Syntax Bug fixes and Presentation Material

-Fixed missing variable declarations for numVar and numBees in
sendEmployedBees

-"Expected one output from a curly brace or dot indexing expression, but
there were 10 results." line 41
v(i,:) = solutionDB.params(randChoice(1,1),:) + (
solutionDB.params(randChoice(1,2),:) -
solutionDB.params(randChoice(1,3),:));

Fixed Result: v(i,:) = solutionDB(randChoice(1)).params +
solutionDB(randChoice(2)).params - solutionDB(randChoice(3)).params;

-"Undefined variable detmat" on line 51 of sendEmployedBees()

-Fixed objFunc by placing anonymous function declaration before m-file
function declaration

-Error  in sendEmployedBees() line 93  "nextGenV = (trialVal .*
decisionFit(:,1)) + ( sampleData .* decisionOrig(:,1));"
sampleData should be origVal

-Error in sendEmployedBees() line 72
should be objFunc(sampleData) instead of objFunc(trialData) to get the
original population's value

-Error in sendOnlookerBees line 47 " q = ( [objValDB.objVal]' -
repmat(valMax, length(solutionDB), 1) ) ./ repmat(valMin - valMax,
length(solutionDB, 1),1);"
Just replace length(solutionDB,1) with length(solutionDB,1)

-Error in sendOnlookerBees line 63, matrix dimension error with subtract
sign, because repmat was not done properly
Fixed that

-Error in line 56 of sendOnlookerBees, randi does not return two
integers without replacement, causing out of bounds index errors in line
63
Replaced randi with randsample

-Error in line 64 of sendOnlookerBees, dec0 and decQ are not repmatted
to ensure matrix dimension compatibility
Corrected Error

-Error in sendOnlookerBees() line 82
should be objFunc(sampleData) instead of objFunc(trialData) to get the
original population's value

-Error in line 98 of sendOnlookerBees()
replace sampleData with origData, since those hold values.

-Error in line 83 of runMB
Should be numScouted instead of newScouts

-Error in line 84 of localImproveBestBee.m
Cells were being indexed improperly.

-Error in RWDE and Direction Exploit
Fixed Incosistencies in Variable Names

* Debugging

Debugged localImproveBestBee(). sendEmployedBees(), sendOnlookerBees()
and runMB(), as well as changed some things in the main to make testing
easier.

* HTML Files Update due to Debugging

Republished edited files

* Debug Part three

Meme Bees is now functional with both the global and local optimization
running without any run-time errors.

Log of changes and errors:

Line 40 of sendEmployedBees in particular is very bad for this.
randSample seems to be very inefficient, and can be replaced by
randPerm.
Line 46 of sendOnlookerBees can also be improved by using randPerm

objFunc also seems to be major source of running time issues. In
particular, the main loop. Vectorizing the loop would probably help
quite a bit.
This can be done by modifying the functions so that they sum or operate
along a certain dimension, and return a column vector.

Takes about 20 mins about 140 variables of Rosenbrock to run, with just
global optimization. This is after vectorizing the function code.

---localImproveBestBee()

Bug: line 93 to line 97 not indexing cells properly. If a is a n by n
cell, a(1,1) is a sub-cell, it does not refer to the value itself
Fix: Use linear indexing with cells, with curly brackets.

Bug: line 77 not indexing cells properly(bestsol(1,1))
Fix: bestsol{1}

Bug: Instances of bestsol being indexed improperly
Fix: Use bestsol{1} or bestsol{2} rather than bestsol(1,1) or
bestsol(1,2);

--sendEmployedBees()
Bug:  line 119 should be objValDB(i).best instead of objValDB(i).objVal
(Your next generation has already been determined by the decision
matrices)

Bug: Line 72 is [origVal] = objFunc(trial);
Fix: Should be [origVal]  = objFunc(sampleData);

Bug: line 118 should be incorrectly references the objective values
rather than the best values
Fix: replace with objValDB(i).best

-sendOnlookerBees()
Bug: line 116 should be objValDB(i).best instead of objValDB(i).objval
(Your next generation has already been determined by the decision
matrices)

Bug: line 82 is [origVal] = objFunc(trial);
Fix: Should be [origval] = objFunc(sampleData);

Bug: line 120 has improper brackets
Fix:  objValDB(i).scouted = objValDB(i).scouted + 1;

-runMB()
Bug: Line 96 does not return the index of minimum. The find function is
not suitable for this task
Fix: Instead, use the multiple output version of the min function.
[valueGlobal,indexGlobal] = min([objValDB.objVal])

Bug: Line 98 is missing square brackets objValDB
Fix: Add the brackets

-----anneal

Error: Referring to objFun rather than objFunc
Fix: Replace with objFunc

---localImproveBestBee

Error: length() has too many arguements, line 84
Fix: Do not understand the issue, replaced with size

Error: anneal() has too many input arguments

Error: Line 99, structure is not being properly assigned to. The problem
is that bestsol{1} is storing multiple indices instead of just one, and
that is causing errors.
This stems from the fact that bestsol{1} is being found using the find
function on line 63. Since there are multiple solutions that are the
best, the find function is giving multiple indices.

--runMB
Added information regarding all the other constants to the display