Debug Part three
Meme Bees is now functional with both the global and local optimization
running without any run-time errors.

Log of changes and errors:

Line 40 of sendEmployedBees in particular is very bad for this.
randSample seems to be very inefficient, and can be replaced by
randPerm.
Line 46 of sendOnlookerBees can also be improved by using randPerm

objFunc also seems to be major source of running time issues. In
particular, the main loop. Vectorizing the loop would probably help
quite a bit.
This can be done by modifying the functions so that they sum or operate
along a certain dimension, and return a column vector.

Takes about 20 mins about 140 variables of Rosenbrock to run, with just
global optimization. This is after vectorizing the function code.

---localImproveBestBee()

Bug: line 93 to line 97 not indexing cells properly. If a is a n by n
cell, a(1,1) is a sub-cell, it does not refer to the value itself
Fix: Use linear indexing with cells, with curly brackets.

Bug: line 77 not indexing cells properly(bestsol(1,1))
Fix: bestsol{1}

Bug: Instances of bestsol being indexed improperly
Fix: Use bestsol{1} or bestsol{2} rather than bestsol(1,1) or
bestsol(1,2);

--sendEmployedBees()
Bug:  line 119 should be objValDB(i).best instead of objValDB(i).objVal
(Your next generation has already been determined by the decision
matrices)

Bug: Line 72 is [origVal] = objFunc(trial);
Fix: Should be [origVal]  = objFunc(sampleData);

Bug: line 118 should be incorrectly references the objective values
rather than the best values
Fix: replace with objValDB(i).best

-sendOnlookerBees()
Bug: line 116 should be objValDB(i).best instead of objValDB(i).objval
(Your next generation has already been determined by the decision
matrices)

Bug: line 82 is [origVal] = objFunc(trial);
Fix: Should be [origval] = objFunc(sampleData);

Bug: line 120 has improper brackets
Fix:  objValDB(i).scouted = objValDB(i).scouted + 1;

-runMB()
Bug: Line 96 does not return the index of minimum. The find function is
not suitable for this task
Fix: Instead, use the multiple output version of the min function.
[valueGlobal,indexGlobal] = min([objValDB.objVal])

Bug: Line 98 is missing square brackets objValDB
Fix: Add the brackets

-----anneal

Error: Referring to objFun rather than objFunc
Fix: Replace with objFunc

---localImproveBestBee

Error: length() has too many arguements, line 84
Fix: Do not understand the issue, replaced with size

Error: anneal() has too many input arguments

Error: Line 99, structure is not being properly assigned to. The problem
is that bestsol{1} is storing multiple indices instead of just one, and
that is causing errors.
This stems from the fact that bestsol{1} is being found using the find
function on line 63. Since there are multiple solutions that are the
best, the find function is giving multiple indices.

--runMB
Added information regarding all the other constants to the display